version: '3.1'

services:
  php-apache:
    build: ./php-apache
    image: php:7.3-apache-mysql
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formbuilder

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db: